backend:
  name: github
  repo: aaronmind/repo
  branch: main
  site_domain: mindmymoney.netlify.app
  display_url: https://aaronmind.github.io/repo/

media_folder: "/assets/images/uploads"

collections:
  - name: "services"
    label: "Services"
    extension: "json"
    delete: false
    preview_path: 'page'
    files:
      - label: "Savings"
        name: "savings"
        file: "/json/savings.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      - label: "Savings For A Home"
        name: "savings-for-home"
        file: "/json/savings-for-home.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      - label: "Investments"
        name: "investments"
        file: "/json/investments.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      - label: "Mortgage Protection"
        name: "mortgage-protection"
        file: "/json/mortgage-protection.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      - label: "One Plan"
        name: "one-plan"
        file: "/json/one-plan-family-first.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      - label: "Pension"
        name: "pension Retirement "
        file: "/json/pensions-retirement-plan-investment.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      - label: "Inheritance"
        name: "inheritance "
        file: "/json/inheritance.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      - label: "Elder Finance"
        name: "elder_finance "
        file: "/json/elder-finance.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      - label: "Life Protection"
        name: "life_protection "
        file: "/json/life-protection.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
          - { label: Label Link 1, name: lLink1, widget: string, required: false}
          - { label: URL Link 1, name: link1, widget: string, required: false}
          - { label: Label Link 2, name: lLink2, widget: string, required: false}
          - { label: URL Link 2, name: link2, widget: string, required: false}
          - { label: Label Link 3, name: lLink3, widget: string, required: false}
          - { label: URL Link 3, name: link3, widget: string, required: false}
          - { label: Label Link 4, name: lLink4, widget: string, required: false}
          - { label: URL Link 4, name: link4, widget: string, required: false}
          - { label: Label Link 5, name: lLink5, widget: string, required: false}
          - { label: URL Link 5, name: link5, widget: string, required: false}
      
	  
