backend:
  name: github
  repo: aaronmind/repo
  branch: main
  site_domain: mindmymoney.netlify.app
  display_url: https://aaronmind.github.io/repo/

media_folder: "/assets/imgages/uploads"

collections:
  - name: "services"
    label: "Services"
    extension: "json"
    editor:
      preview: true
    delete: false
    preview_path: 'page'
    files:
      - label: "Savings"
        name: "savings"
        file: "/json/savings.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
      - label: "Savings For A Home"
        name: "savings-for-home"
        file: "/json/savings-for-home.json"
        allow_add: true
        fields:
          - { label: Title, name: title, widget: string}
          - { label: Body, name: body, widget: markdown}
	  
